// Mocks generated by Mockito 5.4.6 from annotations
// in custom_notify/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:custom_notify/data/services/notification_plugin_service.dart'
    as _i2;
import 'package:custom_notify/domain/services/schedule_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [NotificationPluginService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationPluginService extends _i1.Mock
    implements _i2.NotificationPluginService {
  @override
  set onNotificationTap(_i2.NotificationTapCallback? _onNotificationTap) =>
      super.noSuchMethod(
        Invocation.setter(
          #onNotificationTap,
          _onNotificationTap,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> requestPermissions() => (super.noSuchMethod(
        Invocation.method(
          #requestPermissions,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> scheduleNotification({
    required String? notificationUuid,
    required DateTime? fireTime,
    required String? title,
    required String? body,
    String? soundName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleNotification,
          [],
          {
            #notificationUuid: notificationUuid,
            #fireTime: fireTime,
            #title: title,
            #body: body,
            #soundName: soundName,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cancelNotification({
    required String? notificationUuid,
    required DateTime? fireTime,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelNotification,
          [],
          {
            #notificationUuid: notificationUuid,
            #fireTime: fireTime,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cancelAll() => (super.noSuchMethod(
        Invocation.method(
          #cancelAll,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> getPendingCount() => (super.noSuchMethod(
        Invocation.method(
          #getPendingCount,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<int>> getPendingIds() => (super.noSuchMethod(
        Invocation.method(
          #getPendingIds,
          [],
        ),
        returnValue: _i3.Future<List<int>>.value(<int>[]),
        returnValueForMissingStub: _i3.Future<List<int>>.value(<int>[]),
      ) as _i3.Future<List<int>>);

  @override
  _i3.Future<String?> getNotificationLaunchPayload() => (super.noSuchMethod(
        Invocation.method(
          #getNotificationLaunchPayload,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
        returnValueForMissingStub: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);
}

/// A class which mocks [ScheduleService].
///
/// See the documentation for Mockito's code generation for more information.
class MockScheduleService extends _i1.Mock implements _i4.ScheduleService {
  @override
  _i3.Future<void> syncAll() => (super.noSuchMethod(
        Invocation.method(
          #syncAll,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> syncForItem(String? id) => (super.noSuchMethod(
        Invocation.method(
          #syncForItem,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
